import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Header from "@/components/header";

export const metadata = {
  title: "BoardVault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <Header/>
          <main>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
